### ISSUE TITLE
update SQL speedy method

### ISSUE THREAD

**Issue by CamilaMiorelli** [CamilaMiorelli/moveable_feasts#90]

**Comment by davidlusztig** [comment]
It is not yet needed for our project scope yet. Once we start rendering one to many relations to our show page [for example] then i will implement the optimized rendering on the relevant controller method and on the relevant view page!

**Comment by davidlusztig** [comment]
app/controllers/feasts_controller.rb

`def show
    @feast = Feast.find(params[:id]).includes(:reservations)
  end`

**Comment by davidlusztig** [comment]
added it all.
